"""Deterministic offline provider.

Used when LLM_PROVIDER=stub or no API key is configured, so the demo and the test
suite run with zero external dependencies. Output is obviously synthetic and this
provider reports supports_logprobs = False (it never fabricates perplexity).
"""
from __future__ import annotations

import re

from app.services.llm.base import (
    ClaimExtraction,
    ExtractedClaim,
    LLMProvider,
    LLMResult,
    ProviderCapabilities,
)

_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+")
_NO_ANSWER = "The provided sources do not answer this question."


class StubProvider(LLMProvider):
    name = "stub"

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities(
            supports_logprobs=False,
            supports_embeddings=False,
            supports_structured_output=True,
            supports_streaming=False,
        )

    def generate_answer(self, question: str, sources: list[str]) -> LLMResult:
        joined = " ".join(s.strip() for s in sources if s.strip())
        if not joined:
            text = _NO_ANSWER
        else:
            # Extractive: return the most relevant source sentence(s).
            q_words = {w.lower() for w in re.findall(r"\w+", question) if len(w) > 2}
            best = ""
            best_overlap = -1
            for sent in _SENT_SPLIT.split(joined):
                overlap = len({w.lower() for w in re.findall(r"\w+", sent)} & q_words)
                if overlap > best_overlap:
                    best_overlap, best = overlap, sent
            text = best.strip() or joined[:300]
        return LLMResult(text=text, model="stub-extractive-v1", logprob_available=False)

    def extract_claims(self, question: str, answer: str) -> ClaimExtraction:
        if answer.strip() == _NO_ANSWER or not answer.strip():
            return ClaimExtraction(claims=[], model="stub-extractive-v1")
        sentences = [s.strip() for s in _SENT_SPLIT.split(answer) if len(s.strip()) > 3]
        if not sentences:
            sentences = [answer.strip()]
        claims = [
            ExtractedClaim(text=s, is_critical=(i == 0)) for i, s in enumerate(sentences)
        ]
        return ClaimExtraction(claims=claims, model="stub-extractive-v1")

    def generate_explanation(
        self, label: str, score: int, reasons: list[str], claim_summary: str
    ) -> str:
        reason_txt = "; ".join(reasons) if reasons else "no specific flags"
        return (
            f"This answer was labelled {label} with a reliability score of {score}/100. "
            f"Basis: {reason_txt}. "
            f"Claim support summary: {claim_summary or 'n/a'}. "
            f"(Explanation generated by the offline stub provider.)"
        )
